packages:
  - packages/*
  - playground
  - use-server-directive/*
  - use-server-directive/examples/*
  - use-worker-directive/*
  - use-worker-directive/examples/*

allowBuilds:
  '@sveltejs/kit': true
  esbuild: true
  sharp: true
  svelte-preprocess: true
